name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.0, 8.1, 8.2, 8.3, 8.4]

    steps:
    - uses: actions/checkout@v2

    - name: Generate ssh keygen for the containers interaction
      run: make sshkeygen

    - name: Up containers
      run: docker compose up -d

    - name: Cache vendors
      uses: actions/cache@v4
      env:
        cache-name: cache-vendors
      with:
        path: ~/vendor
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('composer.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install vendors
      run: make composer
      env:
        PHP_VERSION: ${{ matrix.php-version }}

    - name: Check with php-cs-fixer
      run: docker compose run --rm --no-deps dplr vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --show-progress=none -v
      env:
        PHP_VERSION: ${{ matrix.php-version }}

    - name: Run tests
      run: docker compose run --rm --no-deps dplr vendor/bin/phpunit
      env:
        PHP_VERSION: ${{ matrix.php-version }}
